# Generated by Django 5.2.3 on 2025-06-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('bio', models.TextField()),
                ('experience', models.PositiveIntegerField(default=1)),
                ('start_hour', models.TimeField(default='09:00')),
                ('lunch_start', models.TimeField(default='13:00')),
                ('lunch_end', models.TimeField(default='15:00')),
                ('evening_break_start', models.TimeField(default='18:00')),
                ('evening_break_end', models.TimeField(default='18:15')),
                ('end_hour', models.TimeField(default='20:30')),
            ],
        ),
    ]
