# Generated by Django 5.2.3 on 2025-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='photo',
            field=models.ImageField(default='doctors/default.jpg', upload_to='doctors/'),
        ),
    ]
