# Generated by Django 5.2.3 on 2025-06-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
